os: osx
osx_image: xcode9.3
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  bundler: true
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
env:
  global:
  - ANDROID_HOME=/usr/local/share/android-sdk
  - TERM=dumb
  - PATH=$HOME/Library/Python/2.7/bin:$PATH
stages:
- build
- test
before_install:
- bundle install
- brew tap caskroom/cask
- pip install --user awscli
- mkdir -p ~/$TRAVIS_BUILD_NUMBER
- aws s3 sync s3://bugsnag-unity-artifacts/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
after_success:
- aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://bugsnag-unity-artifacts/$TRAVIS_BUILD_NUMBER
jobs:
  include:
  - stage: build
    env:
      - UNITY_VERSION=unity-2017-4-1f1
    script: scripts/travis_build_package.sh
  - stage: test
    env:
      - UNITY_VERSION=unity-2017-4-1f1
    script: scripts/travis_test_package.sh
